name: r-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - bioconda::snakemake
  - r-base=4.5.1
  - r-tidyverse=2.0.0
  - graphviz
  - r-tidyverse
  - r-janitor
  - r-haven
prefix: /home/nojamp/miniconda3/envs/r-env
